### ISSUE TITLE
Issues in event rankings after deleting session

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#138] opened 2023-01-17 08:05 UTC
The data integrity within the event rankings has been improving recently with all of the work by @djong1.

However, the British Speed Challenge is now showing some [issues](https://logiqx.github.io/gp3s-query/gps-speed/events/764.html) for Maciej Bukolt for which I do know the cause. This was caused by Maciej deleting a session that was being used by the event rankings.

The event rankings were previously using a GPX session containing some spurious speeds (e.g. 42 knots 2 sec) which he deleted, after re-posting the FIT file. It would appear the event rankings have not been refreshed for him after the session deletion.

**Comment by Logiqx** [comment] 2023-01-17 08:39
This is probably the cause of the only "ghost" rankings as well:

![image](https://user-images.githubusercontent.com/17449078/212849402-a85fbc45-78a8-423b-862b-531eac5252d0.png)

**Comment by jhdebruin** [comment] 2023-01-17 08:53
Check, i could do a rebuild, but on request of @djong1 i will keep it open just to check what the root cause....

**Comment by Logiqx** [comment] 2023-01-17 09:05
> Check, i could do a rebuild, but on request of @djong1 i will keep it open just to check what the root cause....

Agreed. That's for the best.

**Comment by djong1** [comment] 2023-01-23 07:46
I have done a fix, but the transformation script had a missing selection and it might now cause some unlinked data, can you give me a help by running your script again for the active events? @Logiqx

**Comment by Logiqx** [comment] 2023-01-23 08:29
I've re-run the reports - https://logiqx.github.io/gp3s-query/

It appears to be speed, wing and ice that are showing some data issues.

**Comment by djong1** [comment] 2023-01-25 17:58
@jhdebruin can you give me a help, please rebuild these rankings on a per user basis for these events using the admin module. Thanks

**Comment by jhdebruin** [comment] 2023-01-25 18:18
Yes, for sure , will do some work tonight 🤙

**Comment by jhdebruin** [comment] 2023-01-25 18:49
Done, rebuild on all platforms . @Logiqx  could you kick-off https://logiqx.github.io/gp3s-query/  again to see the results ? Thnx

**Comment by Logiqx** [comment] 2023-01-25 19:54
> Done, rebuild on all platforms . @Logiqx could you kick-off https://logiqx.github.io/gp3s-query/ again to see the results ? Thnx

Done. No errors remaining

**Comment by jhdebruin** [comment] 2023-01-25 20:11
Thx for the fast service ... so @djong1 , all yours to close it !

**Comment by Logiqx** [comment] 2023-01-27 09:15
I've run the reports again, still fine.

**Closed** 2023-01-27 16:33 UTC
Labels: bug, prio-medium
